version: '3'

services:
  web-evinesyalar:
    build: .
    ports:
      - 8091
    volumes:
      - ./evi:/usr/share/nginx/html
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-evinesyalar.rule=Host(`evinesyalar.neyhub.com/`)
      - traefik.http.routers.web-evinesyalar.entrypoints=websecure
      - traefik.http.routers.web-evinesyalar.tls.certResolver=letsencrypt
      - traefik.http.services.web-evinesyalar.loadbalancer.server.port=8091
networks:
  dokploy-network:
    external: true