version: '3.8'

services:
  app-evi:
    build: .
    user: root
    ports:
      - 8081
#    networks:
#      - dokploy-network
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.app-evi.rule=Host(`evinesyalar.neyhub.com`)
#      - traefik.http.routers.app-evi.entrypoints=websecure
#      - traefik.http.routers.app-evi.tls.certResolver=letsencrypt
#      - traefik.http.services.app-evi.loadbalancer.server.port=8080
#networks:
#  dokploy-network:
#    external: true